[build]
  publish = "public"
  command = ""

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://cdn.jsdelivr.net https://telegram.org https://www.googletagmanager.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: https://*.cloudfront.net https://*.amazon.com https://via.placeholder.com https://imagedelivery.net https://upload.wikimedia.org https://github.githubassets.com;
      connect-src 'self' https://genzz-backend.onrender.com https://linkcent.in;
      font-src 'self' https://fonts.gstatic.com;
      media-src 'self' https://static.vecteezy.com;
    """
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=31536000"
